name: test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
jobs:
  change-log:
    runs-on: ubuntu-latest
    steps:
    - name: pr-change-commenter
      uses: Sonichigo/GitHub-Action-s@main
      with:
        owner: ${{ github.repository_owner }}
        repo: ${{ github.event.repository.name }}
        pr_number: ${{ github.event.number }}
